package EDM.edm.main;

import java.io.File;
import java.security.cert.Certificate;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;

import EDM.edm.main.client.ClientProxy;
import EDM.edm.main.handler.config.ConfigCore;
import EDM.edm.main.lib.Library;
import EDM.edm.main.world.WorldGenerator;

import com.google.common.eventbus.EventBus;

import net.minecraft.block.Block;
import static net.minecraft.block.Block.*;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.world.World;
import cpw.mods.fml.common.*;
import cpw.mods.fml.common.Mod.*;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.versioning.ArtifactVersion;
import cpw.mods.fml.common.versioning.VersionRange;

@Mod(modid = Library.modID, name= Library.Name, version=Library.Version, dependencies="required-after:Forge@[9.11.1.953,);required-after:MainCore@{1.1.5.9-S.V.F.C")
@NetworkMod(clientSideRequired=true,serverSideRequired=false)

public class EDMCore extends DummyModContainer
{
	public static CreativeTabs tabEDMBlocks;
	
	@Instance("EDMCore")
	public EDMCore instance;
	
	@SidedProxy(clientSide="EDM.edm.main.client.ClientProxy")
	public static ClientProxy proxy;
	
	@EventHandler
	public static void preload(FMLPreInitializationEvent event)
	{
	    	ModMetadata meta = event.getModMetadata();
			meta.autogenerated = false;
			meta.credits = "(C) Roborave, 2013-2014";
			meta.authorList = Arrays.asList("Roborave");
			meta.name = Library.Name;
			meta.version = Library.Version;
			meta.description = "Made specially for Cliff Sulham. Enjoy!!";
	    
		ConfigCore.loadConfig(event);
		
	}
	
	@EventHandler
	public static void load(FMLInitializationEvent event)
	{
		GameRegistry.registerWorldGenerator(new WorldGenerator());
		proxy.Load();
		
	}
	
	@EventHandler
	public static void postload(FMLPostInitializationEvent event)
	{
		
		
	}

	@Override
	public String getModId() 
	{
		return Library.modid();
	}

	@Override
	public String getName() 
	{
		
		return Library.name();
	}

	@Override
	public String getVersion() 
	{
		return Library.version();
	}

	
}
