package EDM.edm.main;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import net.minecraft.creativetab.CreativeTabs;
import EDM.edm.main.client.ClientProxy;
import EDM.edm.main.handler.config.ConfigCore;
import EDM.edm.main.lib.Library;
import EDM.edm.main.world.WorldGenBlack;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Library.modID, name= Library.Name, version=Library.Version, dependencies="required-after:Forge@[9.11.1.953,);")
@NetworkMod(clientSideRequired=true,serverSideRequired=false)

public class EDMCore extends DummyModContainer
{
	public static CreativeTabs tabEDMBlocks;
	
	@Instance("EDMCore")
	public EDMCore instance;
	
	@SidedProxy(clientSide="EDM.edm.main.client.ClientProxy")
	public static ClientProxy proxy;

	public static final Map<Integer, String> COLOR_MAP = new HashMap<Integer, String>();
	
	@EventHandler
	public static void preload(FMLPreInitializationEvent event)
	{
		
	    	ModMetadata meta = event.getModMetadata();
			meta.autogenerated = false;
			meta.credits = "(C) Roborave, 2013-2014";
			meta.authorList = Arrays.asList("Roborave");
			meta.name = Library.Name;
			meta.version = Library.Version;
			meta.description = "";
	    
		ConfigCore.loadConfig(event);
		
	}
	
	@EventHandler
	public static void load(FMLInitializationEvent event)
	{
		
		proxy.Load();
		
	}
	
	@EventHandler
	public static void postload(FMLPostInitializationEvent event)
	{
		
		
	}

	@Override
	public String getModId() 
	{
		return Library.modid();
	}

	@Override
	public String getName() 
	{
		
		return Library.name();
	}

	@Override
	public String getVersion() 
	{
		return Library.version();
	}

	
}
